### ISSUE TITLE
tlog client on top of tcp/udp dpdk

### ISSUE THREAD

**Issue by iwanbk** [g8os/tlog#45]
We can use mtcp

**Comment by robvanmieghem** [comment]
mtcp ?

**Comment by zielmicha** [comment]
http://shader.kaist.edu/mtcp/

It's used, for example, by Nim tlog server. By I don't understand why we can't use seastar that is used in C++ server.

**Comment by iwanbk** [comment]
```
I don't understand why we can't use seastar that is used in C++ server.
```
because the client is in Go. I don't have idea how to use seastar with it's reactive model from Go

**Comment by iwanbk** [comment]
should be moved to blockstor repo.
